# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SensorService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13SensorService.proto\x12\x0esensor_service\"T\n\x0b\x44ispositivo\x12\x17\n\x0fnomeDispositivo\x18\x01 \x01(\t\x12\x13\n\x0blocalizacao\x18\x02 \x01(\t\x12\x17\n\x0ftipoDispositivo\x18\x03 \x01(\r\"F\n\x11ListaDispositivos\x12\x31\n\x0c\x64ispositivos\x18\x01 \x03(\x0b\x32\x1b.sensor_service.Dispositivo\"o\n\nParametros\x12\x13\n\x0blocalizacao\x18\x01 \x01(\t\x12\x11\n\x04\x64\x61ta\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x1c\n\x0fnomeDispositivo\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x07\n\x05_dataB\x12\n\x10_nomeDispositivo\"v\n\x04\x44\x61\x64o\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x13\n\x0blocalizacao\x18\x03 \x01(\t\x12\x17\n\x0fnomeDispositivo\x18\x04 \x01(\t\x12\x17\n\x0ftipoDispositivo\x18\x05 \x01(\r\x12\r\n\x05valor\x18\x06 \x01(\x02\"1\n\nListaDados\x12#\n\x05\x64\x61\x64os\x18\x01 \x03(\x0b\x32\x14.sensor_service.Dado\"r\n\tLedStatus\x12\x13\n\x06\x65stado\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x1c\n\x0fnomeDispositivo\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x0blocalizacao\x18\x03 \x01(\tB\t\n\x07_estadoB\x12\n\x10_nomeDispositivo\";\n\x0eListaLedStatus\x12)\n\x06status\x18\x01 \x03(\x0b\x32\x19.sensor_service.LedStatus\"\x0e\n\x0c\x45mptyMessage2\xa1\x03\n\rSensorService\x12W\n\x12ListarDispositivos\x12\x1c.sensor_service.EmptyMessage\x1a!.sensor_service.ListaDispositivos\"\x00\x12R\n\x16ListarLeiturasSensores\x12\x1a.sensor_service.Parametros\x1a\x1a.sensor_service.ListaDados\"\x00\x12R\n\x1c\x43onsultarUltimaLeituraSensor\x12\x1a.sensor_service.Parametros\x1a\x14.sensor_service.Dado\"\x00\x12\x44\n\nAcionarLed\x12\x19.sensor_service.LedStatus\x1a\x19.sensor_service.LedStatus\"\x00\x12I\n\nListarLeds\x12\x19.sensor_service.LedStatus\x1a\x1e.sensor_service.ListaLedStatus\"\x00\x42\x37\n\x1bio.grpc.examples.iotserviceB\x0fIoTServiceProtoP\x01\xa2\x02\x04TEMPb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SensorService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.iotserviceB\017IoTServiceProtoP\001\242\002\004TEMP'
  _DISPOSITIVO._serialized_start=39
  _DISPOSITIVO._serialized_end=123
  _LISTADISPOSITIVOS._serialized_start=125
  _LISTADISPOSITIVOS._serialized_end=195
  _PARAMETROS._serialized_start=197
  _PARAMETROS._serialized_end=308
  _DADO._serialized_start=310
  _DADO._serialized_end=428
  _LISTADADOS._serialized_start=430
  _LISTADADOS._serialized_end=479
  _LEDSTATUS._serialized_start=481
  _LEDSTATUS._serialized_end=595
  _LISTALEDSTATUS._serialized_start=597
  _LISTALEDSTATUS._serialized_end=656
  _EMPTYMESSAGE._serialized_start=658
  _EMPTYMESSAGE._serialized_end=672
  _SENSORSERVICE._serialized_start=675
  _SENSORSERVICE._serialized_end=1092
# @@protoc_insertion_point(module_scope)
